// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"
)

type Problem struct {
	ID               int64       `json:"id"`
	ProblemNumber    int64       `json:"problem_number"`
	Title            string      `json:"title"`
	Difficulty       int64       `json:"difficulty"`
	DateAttempted    time.Time   `json:"date_attempted"`
	FirstReviewDate  interface{} `json:"first_review_date"`
	SecondReviewDate interface{} `json:"second_review_date"`
	FinalReviewDate  interface{} `json:"final_review_date"`
	Status           int64       `json:"status"`
	Pattern          *string     `json:"pattern"`
	Notes            *string     `json:"notes"`
	CreatedAt        *time.Time  `json:"created_at"`
	UpdatedAt        *time.Time  `json:"updated_at"`
}
